apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  labels:
    app: nodejs-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nodejs-webapp
    spec:
      containers:
      - name: nodejs-container 
        image: 895072465878.dkr.ecr.us-east-2.amazonaws.com/devops-nodejs:1.01
        imagePullPolicy: Always
        ports:
        - containerPort: 8080